dist: xenial
language: python
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
stages:
  - lint
  - tests
jobs:
  fast_finish: true
  include:
    - stage: lint
      env: TOXENV=check
      python: '3.7'

    - stage: tests
      env: TOXENV=py37
      python: '3.7'
    - env: TOXENV=py38
      python: '3.8'
    - env: TOXENV=py39
      python: '3.9'
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - python -m pip install --progress-bar=off tox
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
